git sudo: required
services:
- docker

before_install:
- docker build -t dinkarinjosh/docker-react -f Dockerfile.dev .

script:
#- docker run dinkarinjosh/docker-react npm run testnowatch
- docker run -e CI=true dinkarinjosh/docker-react npm run test