git sudo: required
services:
- docker

before_install:
- docker build -t dinkarinjosh/docker-react -f Dockerfile.dev .

script:
#- docker run dinkarinjosh/docker-react npm run testnowatch
- docker run  -e CI=true dinkarinjosh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react-learn
  env: "Dockerreactlearn-env-1"
  bucket_name: elasticbeanstalk-us-east-2-318587505622
  bucket_path : docker-react-learn
  on:
    branch : master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY 